### PR TITLE
Implement phone API support

### LINKED ISSUE #404: Implement Phone support from API V6
**Is your feature request related to a problem? Please describe.**

Phone is a new concept introduced in API V6.0. It allows to initiate an authentication order when the user is talking to the RP over the phone. See section 10.2 in the [Relying Party Guidelines V6.0](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v6.0.pdf) for documentation. 

**What area is it related to**
- API
- Core

**Additional context**
PArt of API V6 (#402) but a very specific new feature so we should implement it separately.

### PR DESCRIPTION
**Pull request by nordeke**
This PR fixes #404 .

High level overview of this PR:

- [x] Implemented the 2 (auth/sign) phone API endpoints
- [x] Added tests and some documentation (did I miss anything?)
- [x] Followed same structure as original auth/sign for implementation, request-/response models and tests
- [x] Renamed enum CollectCallInitiator to more general CallInitiator
- [x] Phone auth/sign are tested locally against BankID as well as simulated environment

These things have been implemented (when relevant):

- [x] Code written
- [x] Test added
- [x] Documentation updated / written

### CODE REVIEW

**Comment by PeterOrneholm** [comment]
Great work @nordeke! Just had a quick look and looks great :) Will have to do a deeper review though before we can merge it. Can't promise when we can prioritize that at the moment, but let us know if it is urgent for you and we can find a way.

The one thing I noticed right away is that the API takes a dependency on the Identity library. We have tried to ensure that the API package is very "low level" and does not do to much of validation. We might change this later, but would like to take that away from the API part.

**Comment by nordeke** [comment]
Thank you!

About prioritization, the old functionality with the ability to provide personal identity number will not be supported from BankID after may 1 2024, since "secure start" will be mandatory. (https://www.bankid.com/en/tekniska-uppdateringar/secure-start-will-be-mandatory-from-1-may-2024) It would therefore be appropriate if this functionality could be released some time before that.

I added the reference to Identity just to validate the personal identity number, but I understand your mindset about "low level" and will push a commit removing it.

**Comment by PeterOrneholm** [comment]
Thanks! 

I can't make any promises at the moment, we usually encourage companies to sign up for an support agreement if they need it to be looked at quick.

**Comment by vijng** [comment]
Hi, we have been in contact with ActiveSolution (I guess you know already @PeterOrneholm) about letting them charge us for some consultancy hours to get this in the next release and from the information I received this is scheduled for merge during next week. Please correct me if I am wrong Peter.

Also thank you @nordeke for the PR implementation. Perhaps we can continue in a discussion thread regarding the actual client implementation in order to make the best of the new functionality.

**Comment by PeterOrneholm** [comment]
Hi @vijng and @nordeke! We have scheduled time this wednesday to review, fix any final things, merge and push a new version. Expect a version to be available at latest thursday if we don't find anything blocking us,

**Comment by vijng** [comment]
Great!
________________________________
Från: Peter Örneholm ***@***.***>
Skickat: den 15 april 2024 16:39
Till: ActiveLogin/ActiveLogin.Authentication ***@***.***>
Kopia: Jonas Norberg ***@***.***>; Mention ***@***.***>
Ämne: Re: [ActiveLogin/ActiveLogin.Authentication] Implement phone API support (PR #447)


Hi @vijng<https://github.com/vijng> and @nordeke<https://github.com/nordeke>! We have scheduled time this wednesday to review, fix any final things, merge and push a new version. Expect a version to be available at latest thursday if we don't find anything blocking us,

**Comment by PeterOrneholm** [comment]
We've merged this now. Will wrap up a few things for a v9 release soon.

**Comment by vijng** [comment]
[celebrate]     Jonas Norberg reacted to your message:
________________________________

**Pull request merged**
