### PR TITLE
Add request path base to login and callback path

### PR DESCRIPTION
**Pull request by span**
By adding the path base to the login and callback paths we can support using
routing maps in the `IApplicationBuilder`. Since the default path base is '/' this
should not affect users who have not defined mappings.

This PR solves issue #123

### CODE REVIEW

**Comment by PeterOrneholm** [comment]
Thanks! I will try to review it during the week.

**Comment by fredrik-lundin** [comment]
Thanks a lot for this! I will also try to have a look during the week 😃

**Comment by span** [comment]
Sorry for not rebasing before pushing. I did not realise there were new commits. I can probably do a rebase and force push if you would like to get rid of the merge commit.

**Comment by PeterOrneholm** [comment]
Thankss @span and @fredrik-lundin!

**Comment by PeterOrneholm** [comment]
Don't forget #124 :)

**Comment by PeterOrneholm** [comment]
We plan to release this as part of our 3.0.0 milestone, planned for November/December.

Our 3.0.0 release will require ASP.NET Core 3.X for the UI parts, see details here:
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/109#issuecomment-544378787

Please let me know if this might cause issues for you @span.

**Comment by span** [comment]
No problem for me. Have to move to 3 this autumn anyway. Was hoping that 3.1 would drop in november :)

**Pull request merged**
